### ISSUE TITLE
can't remove firewall package

### ISSUE THREAD

**Issue by brianjmurrell** [aparcar/attendedsysupgrade-server#95] opened 2018-04-24 15:10 UTC
When I try to use the _ImageBuilder_ at https://chef.libremesh.org/ with LEDE and select _Advanced_ to alter package selections, my resulting image has the _firewall_ package installed even though I removed it from the package list.

Trying to utilise _ImageBuilder_'s *-firewall* (remove package) nomenclature in the package list just returns an error.

I know you can remove _firewall_ from LEDE using _ImageBuilder_ since I do it for all of my internal AP builds here for my local network.

Why can't I remove it at https://chef.libremesh.org/ just as easily?

**Comment by jow-** [comment] 2018-04-24 15:19
Maybe you have other meta pacakges selected, like `luci`, `luci-ssl` or `luci-app-firewall` ?

**Comment by aparcar** [comment] 2018-04-24 15:27
> Trying to utilise ImageBuilder's -firewall (remove package) nomenclature in the package list just returns an error.

This is implemented in a different way, whatever package is not in the textarea will be automatically removed from the firmware. This is done via a diff with the "default packages". It was meant to allow package removal without knowing the "default packages" per device. However that might a bit confusing for people used to the pure ImageBuilder.

**Comment by brianjmurrell** [comment] 2018-04-24 16:05
Having to remove _luci_ just to remove _firewall_ is a bit of [throwing the baby out with the bathwater](https://en.wikipedia.org/wiki/Don%27t_throw_the_baby_out_with_the_bathwater).  It should be enough to just not include _luci-app-firewall_ to be able to have _luci_ and not have _firewall_.

But I don't have _luci-app-firewall_ in my list of packages for Chef either.

With ImageBuilder I am able to put `-firewall -luci-app-firewall` in my packages list to remove both of those and still retain _luci_.

**Comment by brianjmurrell** [comment] 2018-05-01 11:04
Any resolution to this, given that the ImageBuilder itself is capable of handling this use-case?

**Comment by aparcar** [comment] 2018-07-20 05:02
@dangowrt can you help out here. If I understood you correctly it's not possible to install the `luci` but remove other packages with are automatically included in it. @brianjmurrell seems to experience a different behavior...

In any case, I'm working on a better version of the server which then allow *negative* packages, if that is then correctly handled by the ImageBuilder is another thing...

**Comment by aparcar** [comment] 2018-08-07 03:42
@brianjmurrell I did some testing but I could not reproduce that behavior with an ImageBuilder. I guessed that the negative packages have be be at the end (at least behind luci), but that does not help neither.

    make image PROFILE="tl-wdr3600-v1" PACKAGES="luci -luci-firewall -firewall"

I close the issue as it's not a fault of the server (if it's a fault after all). If you can provide a working PAKCAGES var I'm happy to implement that with the server

**Comment by brianjmurrell** [comment] 2018-09-11 14:39
This works here:

```
make -C ../openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/ image PROFILE="DIR615C1" PACKAGES="-dnsmasq -firewall -luci-app-firewall ssmtp -kmod-ppp -kmod-pppoe -kmod-pppox -kmod-slhc -ip6tables -iptables -odhcp6c -odhcpd -ppp -ppp-mod-pppoe"
```

None of those packages are added to the image:

```
Building images for ar71xx - D-Link DIR-615 rev. C1
Packages: ssmtp base-files busybox dropbear fstools kernel kmod-ath9k kmod-gpio-button-hotplug libc libgcc logd mtd netifd odhcpd-ipv6only opkg swconfig uboot-envtools uci uclient-fetch wpad-mini


Installing packages...
Installing libc (1.1.19-1) to root...
Installing libgcc (7.3.0-1) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/libgcc_7.3.0-1_mips_24kc.ipk.
Configuring libgcc.
Configuring libc.
Installing kernel (4.9.120-1-c4141763fd59104e24eeb6bb2f68b426) to root...
Configuring kernel.
Installing ssmtp (2.64-5) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/ssmtp_2.64-5_mips_24kc.ipk.
Installing zlib (1.2.11-2) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/zlib_1.2.11-2_mips_24kc.ipk.
Installing libopenssl (1.0.2p-1) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/libopenssl_1.0.2p-1_mips_24kc.ipk.
Installing base-files (192-r7258-5eb055306f) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/base-files_192-r7258-5eb055306f_mips_24kc.ipk.
Installing libubox (2018-07-25-c83a84af-2) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/libubox_2018-07-25-c83a84af-2_mips_24kc.ipk.
Installing libuci (2018-08-11-4c8b4d6e-1) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/libuci_2018-08-11-4c8b4d6e-1_mips_24kc.ipk.
Installing libnl-tiny (0.1-5) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/libnl-tiny_0.1-5_mips_24kc.ipk.
Installing libubus (2018-07-26-40e0931e-1) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/libubus_2018-07-26-40e0931e-1_mips_24kc.ipk.
Installing libjson-c (0.12.1-2) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/libjson-c_0.12.1-2_mips_24kc.ipk.
Installing libblobmsg-json (2018-07-25-c83a84af-2) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/libblobmsg-json_2018-07-25-c83a84af-2_mips_24kc.ipk.
Installing ubusd (2018-07-26-40e0931e-1) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/ubusd_2018-07-26-40e0931e-1_mips_24kc.ipk.
Installing ubus (2018-07-26-40e0931e-1) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/ubus_2018-07-26-40e0931e-1_mips_24kc.ipk.
Installing jshn (2018-07-25-c83a84af-2) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/jshn_2018-07-25-c83a84af-2_mips_24kc.ipk.
Installing netifd (2018-07-30-a0a1e52e-1) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/netifd_2018-07-30-a0a1e52e-1_mips_24kc.ipk.
Installing libjson-script (2018-07-25-c83a84af-2) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/libjson-script_2018-07-25-c83a84af-2_mips_24kc.ipk.
Installing ubox (2018-02-14-128bc35f-2) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/ubox_2018-02-14-128bc35f-2_mips_24kc.ipk.
Installing procd (2018-03-28-dfb68f85-1) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/procd_2018-03-28-dfb68f85-1_mips_24kc.ipk.
Installing jsonfilter (2018-02-04-c7e938d6-1) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/jsonfilter_2018-02-04-c7e938d6-1_mips_24kc.ipk.
Installing usign (2015-07-04-ef641914-1) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/usign_2015-07-04-ef641914-1_mips_24kc.ipk.
Installing openwrt-keyring (2018-05-18-103a32e9-1) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/openwrt-keyring_2018-05-18-103a32e9-1_mips_24kc.ipk.
Installing fstools (2018-04-16-e2436836-1) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/fstools_2018-04-16-e2436836-1_mips_24kc.ipk.
Installing fwtool (1) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/fwtool_1_mips_24kc.ipk.
Installing busybox (1.28.3-4) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/busybox_1.28.3-4_mips_24kc.ipk.
Installing dropbear (2017.75-5.1) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/dropbear_2017.75-5.1_mips_24kc.ipk.
Package fstools (2018-04-16-e2436836-1) installed in root is up to date.
Package kernel (4.9.120-1-c4141763fd59104e24eeb6bb2f68b426) installed in root is up to date.
Installing kmod-ath9k (4.9.120+2017-11-01-9) to root...
Downloading file:packages/kmod-ath9k_4.9.120%2b2017-11-01-9_mips_24kc.ipk
Installing iw (4.14-1) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/iw_4.14-1_mips_24kc.ipk.
Installing wireless-regdb (2017-10-20-4343d359) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/wireless-regdb_2017-10-20-4343d359_mips_24kc.ipk.
Installing kmod-cfg80211 (4.9.120+2017-11-01-9) to root...
Downloading file:packages/kmod-cfg80211_4.9.120%2b2017-11-01-9_mips_24kc.ipk
Installing hostapd-common (2018-04-09-fa617ee6-5) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/hostapd-common_2018-04-09-fa617ee6-5_mips_24kc.ipk.
Installing kmod-mac80211 (4.9.120+2017-11-01-9) to root...
Downloading file:packages/kmod-mac80211_4.9.120%2b2017-11-01-9_mips_24kc.ipk
Installing kmod-ath (4.9.120+2017-11-01-9) to root...
Downloading file:packages/kmod-ath_4.9.120%2b2017-11-01-9_mips_24kc.ipk
Installing kmod-ath9k-common (4.9.120+2017-11-01-9) to root...
Downloading file:packages/kmod-ath9k-common_4.9.120%2b2017-11-01-9_mips_24kc.ipk
Installing kmod-gpio-button-hotplug (4.9.120-2) to root...
Downloading file:packages/kmod-gpio-button-hotplug_4.9.120-2_mips_24kc.ipk
Package libc (1.1.19-1) installed in root is up to date.
Package libgcc (7.3.0-1) installed in root is up to date.
Installing logd (2018-02-14-128bc35f-2) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/logd_2018-02-14-128bc35f-2_mips_24kc.ipk.
Installing mtd (23) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/mtd_23_mips_24kc.ipk.
Package netifd (2018-07-30-a0a1e52e-1) installed in root is up to date.
Installing odhcpd-ipv6only (1.10-1) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/odhcpd-ipv6only_1.10-1_mips_24kc.ipk.
Installing opkg (2017-12-07-3b417b9f-2) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/opkg_2017-12-07-3b417b9f-2_mips_24kc.ipk.
Installing libuclient (2018-08-03-ae1c656f-1) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/libuclient_2018-08-03-ae1c656f-1_mips_24kc.ipk.
Installing uclient-fetch (2018-08-03-ae1c656f-1) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/uclient-fetch_2018-08-03-ae1c656f-1_mips_24kc.ipk.
Installing libpthread (1.1.19-1) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/libpthread_1.1.19-1_mips_24kc.ipk.
Installing swconfig (11) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/swconfig_11_mips_24kc.ipk.
Installing uboot-envtools (2018.03-1) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/uboot-envtools_2018.03-1_mips_24kc.ipk.
Installing uci (2018-08-11-4c8b4d6e-1) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/uci_2018-08-11-4c8b4d6e-1_mips_24kc.ipk.
Package uclient-fetch (2018-08-03-ae1c656f-1) installed in root is up to date.
Installing wpad-mini (2018-04-09-fa617ee6-5) to root...
Copying /net/server/src/openwrt-imagebuilder-18.06.1-ar71xx-tiny.Linux-x86_64/dl/wpad-mini_2018-04-09-fa617ee6-5_mips_24kc.ipk.
Configuring libubox.
Configuring libuclient.
Configuring uclient-fetch.
Configuring libpthread.
Configuring opkg.
Configuring libubus.
Configuring libjson-c.
Configuring libblobmsg-json.
Configuring ubusd.
Configuring ubus.
Configuring libnl-tiny.
Configuring iw.
Configuring busybox.
Configuring libuci.
Configuring swconfig.
Configuring zlib.
Configuring libopenssl.
Configuring ssmtp.
Configuring jshn.
Configuring netifd.
Configuring libjson-script.
Configuring ubox.
Configuring procd.
Configuring jsonfilter.
Configuring usign.
Configuring openwrt-keyring.
Configuring fstools.
Configuring fwtool.
Configuring base-files.
Configuring uboot-envtools.
Configuring wireless-regdb.
Configuring kmod-cfg80211.
Configuring hostapd-common.
Configuring kmod-mac80211.
Configuring kmod-ath.
Configuring kmod-ath9k-common.
Configuring kmod-ath9k.
Configuring uci.
Configuring wpad-mini.
Configuring dropbear.
Configuring mtd.
Configuring odhcpd-ipv6only.
Configuring kmod-gpio-button-hotplug.
Configuring logd.

Finalizing root filesystem...
```

**Comment by brianjmurrell** [comment] 2018-09-11 14:49
Looking at a [build log](https://as-test.stephen304.com/download/openwrt/18.06.1/ar71xx/generic/archer-c7-v2/fb52e20f73d1c28//buildlog-3bff9361af3b7c4.txt) it looks like you are putting removed packages first in the list of packages and then alpha-sorting the remaining list of packages.

Maybe try putting the removed packages at the end of the list instead?

**Comment by aparcar** [comment] 2018-09-12 21:57
@brianjmurrell thanks for further testing, I though the issue would be solved via https://github.com/aparcar/attendedsysupgrade-server/commit/c658031481d85c613c9aaef421ab7b9eba830bbb but it seems most ar71xx/tiny images fail, even tho plenty of packages are removed. You have an idea why it works on your local machine but not on the server?

**Comment by brianjmurrell** [comment] 2018-09-13 14:26
@aparcar Do you have a build run with that patch applied that I can look at the log for?

**Comment by aparcar** [comment] 2018-09-13 15:29
@brianjmurrell see [here](https://as-test.stephen304.com/download/openwrt/18.06.1/ar71xx/generic/tl-wdr4300-v1/c1c0945beb8b88c//buildlog-efc61a4ed777451.txt)
The following line looks as expected, negative packages at the end:

    PACKAGES=wpad-mini uclient-fetch uci uboot-envtools swconfig ppp-mod-pppoe opkg odhcpd-ipv6only odhcp6c netifd mtd logd libgcc kmod-usb2 kmod-usb-ledtrig-usbport kmod-usb-core kmod-gpio-button-hotplug kmod-ath9k ip6tables fstools dropbear busybox base-files -luci -iptables -firewall -dnsmasq

**Comment by brianjmurrell** [comment] 2018-09-13 16:52
Indeed.  And if you look at the build output, you didn't get the _firewall_ package installed -- or any of the others that were excluded.  So that seems to be working.

Except, that when I [try it](https://as-test.stephen304.com/download/openwrt/18.06.1/ar71xx/generic/archer-c7-v2/3c38e2420d88165//buildlog-a67d63f92a97557.txt) even though the list of packages to be excluded is at the end:

```
PACKAGES=wpad-mini uclient-fetch uci uboot-envtools swconfig ppp-mod-pppoe ppp opkg odhcpd-ipv6only odhcp6c netifd mtd luci logd libgcc kmod-usb2 kmod-usb-ledtrig-usbport kmod-usb-core kmod-gpio-button-hotplug kmod-ath9k kmod-ath10k iptables ip6tables fstools firewall dropbear dnsmasq busybox base-files ath10k-firmware-qca988x -luci-app-firewall -firewall -dnsmasq
```

they are still included:

```
Installing firewall (2018-07-26-aa8846bb-1) to root...
Copying /mnt/worker/worker1/imagebuilder/openwrt/18.06.1/ar71xx/generic/dl/firewall_2018-07-26-aa8846bb-1_mips_24kc.ipk.
Installing luci-app-firewall (git-18.247.71242-9541751-1) to root...
Copying /mnt/worker/worker1/imagebuilder/openwrt/18.06.1/ar71xx/generic/dl/luci-app-firewall_git-18.247.71242-9541751-1_all.ipk.
```

although interestingly enough _dnsmasq_ is not installed.

Ahhh.  I see.  In my local builds, I `-luci` but install `luci-base` instead.  So yeah, when I do that with https://as-test.stephen304.com/chef it seems to be working.

So this all seems to be working now.  Can probably close this as resolved with https://github.com/aparcar/attendedsysupgrade-server/commit/c658031481d85c613c9aaef421ab7b9eba830bbb.

**Comment by aparcar** [comment] 2018-09-13 22:12
Thanks for your interest and testing!

**Closed** 2018-09-13 22:12 UTC
